stages:
  - build
  - deploy

build:
  image: node
  stage: build
  before_script:
    - yarn install
  cache:
    paths:
      - node_modules/
  script:
    - npm run generate
  artifacts:
    paths:
      - generate
  only:
    - master

deploy:
  image: debian
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  script:
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete generate/ clients/akaru-starter/; bye"
  only:
    - master
