# Global docker image
image: node

# Stages order
stages:
  - build
  - deploy

# Build job
build:
  stage: build
  before_script:
    - yarn install
  cache:
    paths:
      - node_modules/
  script:
    - npm run generate
  artifacts:
    paths:
      - generate
  only:
    - master

# Deploy job
deploy:
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
  script:
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete generate/ $FTP_PATH; bye"
  only:
    - master
